const ApiPath = {
  AuthApiPath: {
    ADMIN_LOGIN: "users/login",
    VERIFY_OTP: "users/verify-otp",
    RESEND_OTP: "users/resend-otp",
    LOGOUT_ADMIN: "users/logout",
  },
  WebApiPath: {
    DASHBOARD_ADMIN: "dashboard/admin",
    GET_LOGS: "log_activity/all/filtered/logs",
    GET_LOG_USERS: "log_activity/filtered/logs/",
    GET_CUSTOMER_LIST: "users/customer/list",
    DELETE_A_CUSTOMER: "users/",
    SEND_USER_NOTIFICATION: "notifications/custom_notification",
    GET_USER_BY_ID: "users/",
    UPDATE_USER_BY_ID: "user_profiles/",
    ATTACHMENT_UPLOAD: "user_photos/upload",
    GET_SUPERVISOR_LIST: "users/supervisor/list",
    GET_STAFF_LIST: "users/employee/list",
    BLOCK_USER: "block_user/block",
    UNBLOCK_USER: "block_user/unblock",
    GET_USER_PERMISSIONS: "permissions/",
    UPDATE_USER_PERMISSION: "permissions/update/",
    CREATE_SUPERVISOR: "users/create/supervisor",
    UPDATE_STAFF_REQUEST: "users/verify/",
    UPDATE_SKILLS: "user_skills/addDelete",
    GET_JOB_LIST: "jobs/admin",
    GET_TERRITORY_LIST: "territories",
    CREATE_TERRITORY: "territories/create",
    GET_JOBS_BY_ID: "jobs/job",
    SITE: "site/",
    GET_SITE_BY_ID: "site/details/",
    GET_JOBS_BY_ID: "jobs/job/",
    ADD_JOBS: "jobs",
    DELETE_JOB: "jobs/update/job_delete_status/",
    TERRITORY_DELETE: "territories/delete/",
    GET_TERRITORY: "territories/details/",
    UPDATE_TERRITORY: "territories/update/",
    GET_DESIGNATION: "designation",
    ADD_JOB: "jobs/super/user/add/job",
    UPDATE_JOB: "jobs/update_job/",
    EMPLOYEE_LIST_JOB: "jobs/assign/employee/list/",
    ASSIGN_JOB: "jobs/assign/",
    CANCEL_JOB: "jobs/cancel/",
    ROLES: "designation/",
    START_JOB_TIME: "job_hours/super/user/start/job",
    END_JOB_TIME: "job_hours/super/user/end/job/",
    UPDATE_ARCHIVE_STATUS: "users/archive/unarchive/",
    GET_DESIGNATION_BY_ID: "designation/details/",
    CMS: "page/",
    NOTIFICATION: "notifications",
    MARK_ALL_READ : "notifications/update/all",
    MARK_READ : "notifications/",
    SEND_NOTIFICATION_USER : "notifications/custom_notification",
    CHAT_END : "chat/end", 
    ADD_ADMIN : "users/create/sub/admin",
    ADMIN_LIST : "users/sub/admin/list", 
    CALENDAR_JOBS : "jobs/by/territory/"
  },
};

export default ApiPath;
